controller_names:
  - scaled_joint_trajectory_controller
  - joint_trajectory_controller


scaled_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - robot2shoulder_pan_joint
    - robot2shoulder_lift_joint
    - robot2elbow_joint
    - robot2wrist_1_joint
    - robot2wrist_2_joint
    - robot2wrist_3_joint


joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - robot2shoulder_pan_joint
    - robot2shoulder_lift_joint
    - robot2elbow_joint
    - robot2wrist_1_joint
    - robot2wrist_2_joint
    - robot2wrist_3_joint
